# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # add data product
        self.products = [
            {"name": "Shampo", "price": 20000, "stock": 10},
            {"name": "Beras", "price": 15000, "stock": 10},
            {"name": "Minyak Goreng", "price": 30000, "stock": 10},
            {"name": "Sabun Mandi", "price": 10000, "stock": 10},
            {"name": "Mie Sedap", "price": 5000, "stock": 10},
            {"name": "Indomie", "price": 5000, "stock": 10},
            {"name": "Mie Sukses", "price": 5000, "stock": 10},
            {"name": "Kecap ABC", "price": 10000, "stock": 10},
            {"name": "Kurma", "price": 30000, "stock": 10},
        ]
        self.cart = []

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 881, 821))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameApp = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.nameApp.setFont(font)
        self.nameApp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nameApp.setAlignment(QtCore.Qt.AlignCenter)
        self.nameApp.setObjectName("nameApp")
        self.verticalLayout.addWidget(self.nameApp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.textProduct = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.textProduct.setObjectName("textProduct")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textProduct)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("padding: 4px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.textQuantity = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.textQuantity.setObjectName("textQuantity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.textQuantity)
        self.quantity = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.quantity.setStyleSheet("padding: 4px")
        self.quantity.setObjectName("quantity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.quantity)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.textDiscount = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.textDiscount.setObjectName("textDiscount")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.textDiscount)
        self.discount = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.discount.setStyleSheet("padding: 4px")
        self.discount.setObjectName("discount")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.discount)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.addBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addBtn.setEnabled(True)
        self.addBtn.setStyleSheet("padding: 4px")
        self.addBtn.setObjectName("addBtn")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.addBtn)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 7, 0, 1, 1)
        self.textCreated = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textCreated.setFont(font)
        self.textCreated.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.textCreated.setObjectName("textCreated")
        self.gridLayout.addWidget(self.textCreated, 13, 0, 1, 1)
        self.listProduct = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.listProduct.setObjectName("listProduct")
        self.listProduct.setColumnCount(4)
        self.listProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(217, 217, 217))
        self.listProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listProduct.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.listProduct, 2, 0, 5, 5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.note = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.note.setFont(font)
        self.note.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 0, 0, 1, 1)
        self.checkBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.checkBtn.setStyleSheet("padding: 4px")
        self.checkBtn.setObjectName("checkBtn")
        self.gridLayout.addWidget(self.checkBtn, 11, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textTotal = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.textTotal.setObjectName("textTotal")
        self.horizontalLayout.addWidget(self.textTotal)
        self.price = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.price.setObjectName("price")
        self.horizontalLayout.addWidget(self.price)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 12, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 4, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 10, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 8, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.myName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.myName.setFont(font)
        self.myName.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.myName.setObjectName("myName")
        self.verticalLayout.addWidget(self.myName)
        self.myNIM = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.myNIM.setFont(font)
        self.myNIM.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.myNIM.setObjectName("myNIM")
        self.verticalLayout.addWidget(self.myNIM)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameApp.setText(_translate("MainWindow", "POS Application"))
        self.textProduct.setText(_translate("MainWindow", "Product"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose product"))
        self.textQuantity.setText(_translate("MainWindow", "Quantity"))
        self.textDiscount.setText(_translate("MainWindow", "Discount"))
        self.addBtn.setText(_translate("MainWindow", "Add to Cart"))
        self.textCreated.setText(_translate("MainWindow", "Created by"))
        item = self.listProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product"))
        item = self.listProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.listProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Discount"))
        item = self.listProduct.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.note.setText(_translate("MainWindow", "Shopping Receipt"))
        self.checkBtn.setText(_translate("MainWindow", "Checkout"))
        self.textTotal.setText(_translate("MainWindow", "Total price"))
        self.price.setText(_translate("MainWindow", "Rp 0"))
        self.myName.setText(_translate("MainWindow", "M. Ilham Abdul Shaleh"))
        self.myNIM.setText(_translate("MainWindow", "F1D022061"))

        #   implement logic
        self.addBtn.clicked.connect(self.addToCart)
        self.checkBtn.clicked.connect(self.checkout)
        self.populateProducts()


    #     add logic function
    def populateProducts(self):
        self.comboBox.clear()
        self.comboBox.addItem("Choose product")
        for product in self.products:
            self.comboBox.addItem(f"{product['name']} - Rp {product['price']} (Stok: {product['stock']})")

    # functio to nambah ke cart
    def addToCart(self):
        # get index-nya
        selected_index = self.comboBox.currentIndex() - 1

        # nilai input jumlah sama diskon
        quantity = self.quantity.value()
        discount = self.discount.value()

        # validasi
        if selected_index >= 0:
            product = self.products[selected_index]

            # cek stok
            if product['stock'] >= quantity:
                # stok kurangi
                product['stock'] -= quantity

                # hitung dengan diskon
                total_price = product['price'] * quantity * (1 - discount / 100)

                # tambahin ke cart
                cart_item = {
                    "name": product['name'],
                    "price": product['price'],
                    "quantity": quantity,
                    "discount": discount,
                    "total_price": total_price
                }
                self.cart.append(cart_item)

                # update list product
                self.updateCartTable()

                # update total harga (default Rp 0)
                self.updateTotal()

                # refresh data product (stokny berkurang atau tidak)
                self.populateProducts()

                # pop up berhasil
                QtWidgets.QMessageBox.information(None, "Konfirmasi", "Produk berhasil ditambahkan!")
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan",
                                              f"Stok tidak mencukupi! Tersedia {product['stock']} produk.")
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Pilih produk terlebih dahulu!")

    # manipulasi list product
    def updateCartTable(self):
        self.listProduct.setRowCount(0)

        # isi dengan product
        for item in self.cart:
            row_position = self.listProduct.rowCount()
            self.listProduct.insertRow(row_position)

            # add data ke tabel
            self.listProduct.setItem(row_position, 0, QtWidgets.QTableWidgetItem(str(item['name'])))
            self.listProduct.setItem(row_position, 1, QtWidgets.QTableWidgetItem(str(item['quantity'])))
            self.listProduct.setItem(row_position, 2, QtWidgets.QTableWidgetItem(f"{item['discount']}%"))
            self.listProduct.setItem(row_position, 3, QtWidgets.QTableWidgetItem(f"Rp {item['total_price']:,.0f}"))


    # untuk itung total keseluruhan
    def updateTotal(self):
        # hitung total semua harga product di cart
        total_price = sum(item['total_price'] for item in self.cart)

        # update total harga
        self.price.setText(f"Rp {total_price:,.0f}")

    # untuk checkout
    def checkout(self):
        # validate
        if not self.cart:
            QtWidgets.QMessageBox.warning(None, "Keranjang Kosong", "Tidak ada produk di keranjang!")
            return

        # hitung keseluruhan
        total_price = sum(item['total_price'] for item in self.cart)

        # konfirmasi checkout
        reply = QtWidgets.QMessageBox.question(
            None,
            "Konfirmasi Checkout",
            f"Total belanja: Rp {total_price:,.0f}\nLanjutkan checkout?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )

        # proses checkout
        if reply == QtWidgets.QMessageBox.Yes:
            # reset keranjang dan tabel
            self.cart.clear()
            self.listProduct.setRowCount(0)
            self.price.setText("Rp 0")

            # pop up berhasil
            QtWidgets.QMessageBox.information(None, "Berhasil", "Checkout berhasil!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
